### ISSUE TITLE
Incorrect checksums in v45.0.0 and v45.0.1

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-native-ios#3]
v45.0.0 and v45.0.1 have incorrect checksums (compare to v44.0.0, which matches):

Version | Expected | Actual
----|----|----
v44.0.0 | `5004117a2bdd1b43f72793c71ff393e2873296a4b3420fbeda1038e8925a315c` | https://github.com/mapbox/mapbox-navigation-native-ios/blob/f1cb05467fdd607fc23c065c56e71f74c14c550d/Package.swift#L9
v45.0.0 | `fe36cf1b5a67ec0bbce5883850803789cda3d7682b91697c0a6bf34adfad0d23` | https://github.com/mapbox/mapbox-navigation-native-ios/blob/5a1849aec03536aab6cde3dd175b828adbbbed95/Package.swift#L9
v45.0.1 | `feefa910c95e1dead8668a7d8a871b243a3fa688fed85b66c1483d0c33254bb1` | https://github.com/mapbox/mapbox-navigation-native-ios/blob/3d6221c357cd9f7604dd384bdd9cb1286fe44ea9/Package.swift#L9

```bash
curl https://api.mapbox.com/downloads/v2/mobile-navigation-native/releases/ios/packages/$VERSION/MapboxNavigationNative.xcframework.zip?access_token=$ACCESS_TOKEN
swift package compute-checksum MapboxNavigationNative.xcframework.zip 
```

/cc @mapbox/navigation-ios @mapbox/navnative

**Comment by 1ec5** [comment]
@etl pushed v45.0.2 with the fix in #4. This means the next normal release cannot be v45.0.2.

**Comment by etl** [comment]
Bug is in `release.sh`. No checking for absent artifact in SDK registry.
hash of {"message":"Not Found"} = 8fd54eee4277f1327015cc0bcaed8a878bf44d1804364cd5d93dfab9e2d1a5af

**Comment by truburt** [comment]
@etl, just to clarify - what artifacts were missing and why?

**Comment by etl** [comment]
Most probably when we deploy artifacts to SDK registry it takes some time until they checked and available. Script should wait until they are actually downloadable AND check for network errors. Now curl just gets error message and saves to a 'binary' file, next `swift package compute-checksum` just hashes this text file with AES without any additional checking.

**Comment by zugaldia** [comment]
Thank you @etl for the quick eyes. Please consider this issue as release blocking.
